### ISSUE TITLE
Hostname variable

### ISSUE THREAD

**Issue by metafarion** [silverwizard/pod2mpd#3]
Script works pretty well!  I did have to add a -h $mpdhost switch to the mpc execution command to tell it which mpd server to connect to.

**Comment by silverwizard** [comment]
Did you end up with a solid version?

I will happily take a pull request, but don't touch this repo much.

**Comment by metafarion** [comment]
I...uhh.... actually don't really know how to use Github :-P
My contributions thus far have been limited to sprinkling complaints and suggestions here and there.

**Comment by silverwizard** [comment]
Don't worry - neither do I ;)

Updated!
